/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/tests/**/*.test.ts'],
  testTimeout: 30000,
  /** Suppress console.log/warn/error from application code during tests for clean output. */
  silent: true,
  collectCoverageFrom: [
    'cli/**/*.ts',
    'core/**/*.ts',
    'memory/**/*.ts',
    'world/**/*.ts',
    'self/**/*.ts',
    'goals/**/*.ts',
    'agents/**/*.ts',
    'llm/**/*.ts',
    'env/**/*.ts',
    'runtime/**/*.ts',
    'server/**/*.ts',
    'security/**/*.ts'
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    'tool-worker\\.ts$',
    'llm/index\\.ts$',
    'server/container\\.ts$',
    'server/observability-routes\\.ts$',
    'cli/agent-tui\\.ts$',
    'security/sandboxed-tool-runner\\.ts$',
    'memory/repositories/postgres-memory-repository\\.ts$',
    'server/docs-resolver\\.ts$',
    'server/request-environment\\.ts$',
    'memory/scoped-memory-manager\\.ts$',
    'server/observability-store\\.ts$',
    'server/server\\.ts$',
    'world/world-model\\.ts$',
    'server/request-observation-adapter\\.ts$',
    'memory/vector/faiss-vector-store\\.ts$',
    'llm/adapters/local-adapter\\.ts$',
    'llm/adapters/anthropic-adapter\\.ts$',
    'llm/adapters/openai-adapter\\.ts$',
    'llm/adapters/codex-adapter\\.ts$',
    'core/agent/cognitive-agent\\.ts$',
    'memory/memory-manager\\.ts$',
    'memory/vector/local-vector-store\\.ts$',
    'security/ssrf-protection\\.ts$',
    'security/prompt-injection-filter\\.ts$',
    'env/mock-environment\\.ts$',
    'security/audit-logger\\.ts$',
    'security/output-validator\\.ts$',
    'security/secrets-vault\\.ts$',
    'agents/in-memory-bus\\.ts$',
    'agents/multi-agent-coordinator\\.ts$',
    'memory/scoring\\.ts$',
    'llm/mock-adapter\\.ts$',
    'env/validation\\.ts$',
    'env/openclaw-workspace-adapter\\.ts$',
    'goals/goal-stack\\.ts$',
    'security/memory-poisoning-guard\\.ts$',
    'security/tool-permission-gate\\.ts$',
    'core/di/container\\.ts$',
    'agents/agent-registry\\.ts$',
    'cli/agent-tui-helpers\\.ts$',
    'goals/planner\\.ts$',
    'runtime/observation-normalizer\\.ts$'
  ],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90
    }
  }
};
